---
title: "Plotting gene expression in R"
author: "Kelly Sovacool and Audrey Drotos"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true 
    toc_float:
      collapsed: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      fig.path = 'figures/')
```

# RStudio

```{r}
# WALKING THROUGH RSTUDIO:
# open a new project
# console
# global environment
# scripting space
# plot and help viewer

```

# R as a calculator

```{r}

# Using R as a calculator
# addition  +
5 + 3
# subtraction -
5 - 3
# multiplication *
5 * 3
# division /
5 / 3

# mod (remainder) %%
5 %% 3

#exponent
5 ** 3
5 ^3

#combining terms together (PEMDAS)
5 - 3^2
(5-3) ^ 2

```

# Variables
```{r}

# VARIABLES:
weight_kg <- 55
# the assignment operator

#print to console
weight_kg
print(weight_kg)

#weight in pounds
weight_lb <- 2.2 * weight_kg
weight_lb

2.2*55

weight_kg <- 100
weight_lb
weight_lb <- weight_kg * 2.2
weight_lb
```

# Functions
TODO
sum, mean, median

# Packages
```{r}
# Load tidyverse packages
#install.packages(c('tidyverse', 'readxl'))
library(tidyverse) # We need a package to read in an excel sheet. Go over packages
library(readxl)
```

# Loading data

```{r}

# READING DATA INTO R
# READ IN EXCEL FILES <- functions
# TODO: use URL of spreadsheet
six_weeks <- read_excel('data/log2_expression_6wks.xlsx', sheet = 1)
twenty_four_weeks <- read_excel('data/log2_expression_24wks.xlsx', sheet = 1)

```

# Data frames

```{r, eval = FALSE}
# LOOKING AT OUR DATA
View(six_weeks)
View(twenty_four_weeks)
```

```{r}
head(six_weeks)
ncol(six_weeks)
nrow(six_weeks)
dim(six_weeks)
colnames(six_weeks)
rownames(six_weeks)

#reference things in the data frame
#data_frame[row,column]
dim(six_weeks)
six_weeks[1,1]
six_weeks[5,]
six_weeks[,5]
six_weeks[,2]
six_weeks$ACTN2
```

```{r}
# USING FUNCTIONS
mean(six_weeks$ACTN2)
mean(twenty_four_weeks$ACTN2)

summary(six_weeks$ACTN2)
summary(twenty_four_weeks$ACTN2)
```

# Data manipulation

## pivot

```{r}
# pivot longer
dat_long_6wks <- six_weeks %>%
    pivot_longer(-Sample_Num, names_to = "gene", values_to = '6')
dat_long_24wks <- twenty_four_weeks %>%
    pivot_longer(-Sample_Num, names_to = "gene", values_to = '24')

```

## join

```{r}
# join
dat_joined <- full_join(dat_long_6wks, dat_long_24wks, by = c('Sample_Num', 'gene'))

```

```{r}
# pivot longer again
dat_joined_long <- dat_joined %>% pivot_longer(c('6', '24'),
                                               names_to = 'weeks',
                                               values_to = 'log2_expr')
```


# Your first boxplot

```{r boxplot-actn2}
dat_joined_long %>%
    filter(gene == 'ACTN2') %>%
    ggplot(aes(weeks, log2_expr)) +
    geom_boxplot() +
    labs(title = 'ACTN2')
```


## Saving plots

```{r, eval = FALSE}
boxplot_actn2 <- dat_joined_long %>%
    filter(gene == 'ACTN2') %>%
    ggplot(aes(weeks, log2_expr)) +
    geom_boxplot() +
    labs(title = 'ACTN2')
ggsave(filename = 'boxplot_actn2.png', plot = boxplot_actn2)
```


```{r}
# CHALLENGE:
# Make a boxplot plot for expression of the gene GATA4 at 6 weeks compared to 24 weeks.
```

# Color palettes

```{r}
# R color palettes
# change the colors with scale_color_
```

```{r}
# CHALLENGE:
# modify your boxplot for GATA4. make each box a different color. 
# bonus: pick two of your favorite colors from TODO URL
```


# Plot all the genes

```{r boxplot-all-genes}
# PLOT ALL THE GENES
# facet wrap
dat_joined_long %>%
    ggplot(aes(weeks, log2_expr)) +
    geom_boxplot() +
    facet_wrap('gene')
```

# Heatmaps

```{r heatmap-6-weeks}
dat_joined_long %>%
    filter(weeks == '6', !is.na(log2_expr)) %>%
    ggplot(aes(gene, Sample_Num, fill = log2_expr)) +
    geom_tile() +
    theme(axis.text.x = element_text(angle = 90))
```

```{r heatmap-24-weeks}
dat_joined_long %>%
    filter(weeks == '24', !is.na(log2_expr)) %>%
    ggplot(aes(gene, Sample_Num, fill = log2_expr)) +
    geom_tile() +
    theme(axis.text.x = element_text(angle = 90))
```


TODO: interesting genes for hearts, cellular development, division?

